import type { Metadata } from "next"

export const siteConfig = {
	name: "Anghelo Alva",
	description:
		"Soy Anghelo Alva, desarrollador full stack. Construyo software a medida de extremo a extremo —del levantamiento de requerimientos al soporte en producción— para empresas de energía, minería, turismo y educación.",
	url: "https://angheloalva.dev",
	creator: "Anghelo Alva",
	authors: [
		{
			name: "Anghelo Alva",
			url: "https://angheloalva.dev",
		},
	],
	keywords: [
		"Anghelo Alva",
		"desarrollador full stack",
		"Next.js",
		"React",
		"TypeScript",
		"NestJS",
		"PostgreSQL",
		"portafolio",
		"Chile",
	],
} as const

export const baseMetadata: Metadata = {
	metadataBase: new URL(siteConfig.url),
	title: {
		default: `${siteConfig.name} — Desarrollador Full Stack`,
		template: `%s | ${siteConfig.name}`,
	},
	description: siteConfig.description,
	keywords: [...siteConfig.keywords],
	authors: [...siteConfig.authors],
	creator: siteConfig.creator,
	publisher: siteConfig.name,
	robots: {
		index: true,
		follow: true,
		googleBot: {
			"index": true,
			"follow": true,
			"max-video-preview": -1,
			"max-image-preview": "large",
			"max-snippet": -1,
		},
	},
	alternates: {
		canonical: "/",
	},
	openGraph: {
		type: "website",
		locale: "es_CL",
		url: siteConfig.url,
		title: siteConfig.name,
		description: siteConfig.description,
		siteName: siteConfig.name,
		// og:image is generated by app/opengraph-image.tsx (file convention).
	},
	twitter: {
		card: "summary_large_image",
		title: siteConfig.name,
		description: siteConfig.description,
	},
	icons: {
		icon: [
			{ url: "/favicon.svg", type: "image/svg+xml" },
			{ url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
			{ url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
		],
		shortcut: "/favicon-32x32.png",
		apple: "/apple-touch-icon.png",
	},
	manifest: "/site.webmanifest",
}

export function createMetadata({
	title,
	description,
	path = "/",
	image,
	noIndex = false,
}: {
	title?: string
	description?: string
	path?: string
	image?: string
	noIndex?: boolean
}): Metadata {
	const url = `${siteConfig.url}${path}`

	return {
		title,
		description,
		alternates: {
			canonical: path,
		},
		openGraph: {
			title: title ?? siteConfig.name,
			description: description ?? siteConfig.description,
			url,
			// Only override the generated OG image (app/opengraph-image.tsx) when an
			// explicit image is provided; otherwise let the file convention apply.
			...(image && {
				images: [
					{
						url: image,
						width: 1200,
						height: 630,
						alt: title ?? siteConfig.name,
					},
				],
			}),
		},
		twitter: {
			title: title ?? siteConfig.name,
			description: description ?? siteConfig.description,
			...(image && { images: [image] }),
		},
		...(noIndex && {
			robots: {
				index: false,
				follow: false,
			},
		}),
	}
}
